apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-nginx
spec:
  containers:
  - name: test-pvc-nginx
    image: nginx:1.19
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: "/test/volume"
        name: test-pv
  volumes:
  - name: test-pv
    persistentVolumeClaim:
      claimName: test-pvc
